import '../styles/globals.css'
// import { Inter } from '@/next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Student Project Tracking System',
  description: 'Generated by 2019 batch students',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
