export const itemData = [
    { 
        image: '/protol.png',
        title: 'Hotel Reservation System',
        date: 'Jan 14, 2022',
        href: '/project-detail/hotelDetail',
        cname: 'col-span-2 shadow-lg pb-5 mb-5 gap-x-4 ml-12 w-96',
        description: 'lorem ipsum is simply dummy text of the printing and typesetting industry. it has been the industrys standard dummy text ever since 1500s.',
    },
    {
        image: '/rateeat.jpg',
        title: 'Rate Eat',
        date: 'Sep 9, 2022',
        href: '/project-detail/rateeatDetail',
        cname: 'col-span-2 shadow-lg pb-5 mb-5 gap-x-4 ml-12 w-96',
        description: 'lorem ipsum is simply dummy text of the printing and typesetting industry. it has been the industrys standard dummy text ever since 1500s.',
    },
    {
        image: '/labconnect.png',
        title: 'Lab Connect',
        date: 'Jan 14, 2021',
        href: '/project-detail/rateeatDetail',
        cname: 'col-span-2 shadow-lg pb-5 mb-5 gap-x-4 ml-12 w-96',
        description: 'lorem ipsum is simply dummy text of the printing and typesetting industry. it has been the industrys standard dummy text ever since 1500s.',
    },
    {
        image: '/specialsecurity.png',
        title: 'Special Security Services',
        date: 'Jan 14, 2021',
        href: '/project-detail/rateeatDetail',
        cname: 'col-span-2 shadow-lg pb-5 mb-5 gap-x-4 ml-12 w-96',
        description: 'lorem ipsum is simply dummy text of the printing and typesetting industry. it has been the industrys standard dummy text ever since 1500s.',
    },
    {
        image: '/atrons.png',
        title: 'Atrons',
        date: 'Jan 14, 2021',
        href: '/project-detail/rateeatDetail',
        cname: 'col-span-2 shadow-lg pb-5 mb-5 gap-x-4 ml-12 w-96',
        description: 'lorem ipsum is simply dummy text of the printing and typesetting industry. it has been the industrys standard dummy text ever since 1500s.',
    },
    {
        image: '/capsule.png',
        title: 'Real Estate Management System',
        date: 'Jan 14, 2021',
        href: '/project-detail/realestateDetail',
        cname: 'col-span-2 shadow-lg pb-5 mb-5 gap-x-4 ml-12 w-96',
        description: 'lorem ipsum is simply dummy text of the printing and typesetting industry. it has been the industrys standard dummy text ever since 1500s.',
    },
]
